import Plato from '../interfaces/plato.interface';

export const Bebidas: Plato[] = [
  { nombre: 'plato1', alergenos: [0], precioMedia: '1/2R', precioEntera: '1R' },
  { nombre: 'plato2', alergenos: [0], precioMedia: 'X', precioEntera: '1.70' },
  { nombre: 'plato3', alergenos: [0], precioMedia: 'X', precioEntera: '2.00' },
  { nombre: 'plato4', alergenos: [0], precioMedia: 'X', precioEntera: '1.50' },
  { nombre: 'plato5', alergenos: [0], precioMedia: 'X', precioEntera: '2.50' },
  { nombre: 'plato6', alergenos: [0], precioMedia: 'X', precioEntera: '1.50' },
  { nombre: 'plato7', alergenos: [0], precioMedia: 'X', precioEntera: '2.50' },
  { nombre: 'plato8', alergenos: [0], precioMedia: 'X', precioEntera: '2.0' },
  { nombre: 'plato9', alergenos: [0], precioMedia: 'X', precioEntera: '2.50' },
  { nombre: 'plato10', alergenos: [0], precioMedia: 'X', precioEntera: '1.50' },
  { nombre: 'plato11', alergenos: [0], precioMedia: 'X', precioEntera: '1.50' },
  { nombre: 'plato12', alergenos: [0], precioMedia: 'X', precioEntera: '3.00' },
  { nombre: 'plato13', alergenos: [0], precioMedia: 'X', precioEntera: '3.00' },
  { nombre: 'plato14', alergenos: [0], precioMedia: 'X', precioEntera: '2.00' },
  { nombre: 'plato15', alergenos: [0], precioMedia: 'X', precioEntera: '2.00' },
  { nombre: 'plato16', alergenos: [0], precioMedia: 'X', precioEntera: '3.00' },
  { nombre: 'plato17', alergenos: [0], precioMedia: 'X', precioEntera: '3.00' },
  { nombre: 'plato18', alergenos: [0], precioMedia: 'X', precioEntera: '2.50' },
  { nombre: 'plato19', alergenos: [0], precioMedia: 'X', precioEntera: '3.75' },
  { nombre: 'plato20', alergenos: [0], precioMedia: 'X', precioEntera: '6.00' },
  { nombre: 'plato21', alergenos: [0], precioMedia: 'X', precioEntera: '12.00' },
  { nombre: 'plato22', alergenos: [0], precioMedia: 'X', precioEntera: '2.50' },
  { nombre: 'plato23', alergenos: [0], precioMedia: 'X', precioEntera: '3.50' },
  { nombre: 'plato24', alergenos: [0], precioMedia: 'X', precioEntera: '2.50' },
  { nombre: 'plato25', alergenos: [0], precioMedia: 'X', precioEntera: '3.00' },
  { nombre: 'plato26', alergenos: [0], precioMedia: 'X', precioEntera: '11.00' },
  { nombre: 'plato27', alergenos: [0], precioMedia: 'X', precioEntera: '14.00' },
  { nombre: 'plato28', alergenos: [0], precioMedia: 'X', precioEntera: '3.50' },
  { nombre: 'plato29', alergenos: [0], precioMedia: 'X', precioEntera: '2.00' },
  { nombre: 'plato30', alergenos: [0], precioMedia: 'X', precioEntera: '4.00' },
  { nombre: 'plato31', alergenos: [0], precioMedia: 'X', precioEntera: '4.00' },
  { nombre: 'plato32', alergenos: [0], precioMedia: 'X', precioEntera: '4.00' },
  { nombre: 'plato33', alergenos: [3], precioMedia: 'X', precioEntera: '6.00' },
  { nombre: 'plato34', alergenos: [0], precioMedia: 'X', precioEntera: '6.00' },
  { nombre: 'plato35', alergenos: [0], precioMedia: 'X', precioEntera: '6.00' },
  { nombre: 'plato36', alergenos: [0], precioMedia: 'X', precioEntera: '6.00' },
  { nombre: 'plato37', alergenos: [0], precioMedia: 'X', precioEntera: '3.50' },
  { nombre: 'plato38', alergenos: [0], precioMedia: 'X', precioEntera: '6.00' },
  { nombre: 'plato39', alergenos: [0], precioMedia: 'X', precioEntera: '6.00' },
  { nombre: 'plato40', alergenos: [0], precioMedia: 'X', precioEntera: '6.00' },
  { nombre: 'plato41', alergenos: [0], precioMedia: 'X', precioEntera: '8.00' },
  { nombre: 'plato42', alergenos: [0], precioMedia: 'X', precioEntera: '6.00' },
  { nombre: 'plato43', alergenos: [0], precioMedia: 'X', precioEntera: '3.50' },
  { nombre: 'plato44', alergenos: [0], precioMedia: 'X', precioEntera: '3.50' },
]
