import Plato from '../interfaces/plato.interface';

export const Desayunos: Plato[] = [
  { nombre: 'plato1', alergenos: [0], precioMedia: '1/2R', precioEntera: '1R' },
  { nombre: 'plato2', alergenos: [0], precioMedia: 'X', precioEntera: '1.90' },
  { nombre: 'plato3', alergenos: [0], precioMedia: 'X', precioEntera: '2.00' },
  { nombre: 'plato4', alergenos: [0], precioMedia: 'X', precioEntera: '2.70' },
  { nombre: 'plato5', alergenos: [0], precioMedia: 'X', precioEntera: '3.00' },
  { nombre: 'plato6', alergenos: [0], precioMedia: 'X', precioEntera: '2.00' },
  { nombre: 'plato7', alergenos: [0], precioMedia: 'X', precioEntera: '2.50' },
  { nombre: 'plato8', alergenos: [0], precioMedia: 'X', precioEntera: '3.50' },
  { nombre: 'plato9', alergenos: [0], precioMedia: 'X', precioEntera: '2.80' },
  { nombre: 'plato10', alergenos: [0], precioMedia: 'X', precioEntera: '2.80' },
  { nombre: 'plato11', alergenos: [1], precioMedia: 'X', precioEntera: '2.80' },
  { nombre: 'plato12', alergenos: [1], precioMedia: 'X', precioEntera: '3.50' },
  {
    nombre: 'plato13',
    alergenos: [1],
    precioMedia: 'X',
    precioEntera: '10.50',
  },
  { nombre: 'plato14', alergenos: [1], precioMedia: 'X', precioEntera: '7.00' },
  {
    nombre: 'plato15',
    alergenos: [1, 7, 12],
    precioMedia: 'X',
    precioEntera: '6.00',
  },
  {
    nombre: 'plato16',
    alergenos: [1, 12],
    precioMedia: 'X',
    precioEntera: '5.00',
  },
  {
    nombre: 'plato17',
    alergenos: [1, 7, 12],
    precioMedia: 'X',
    precioEntera: '7.00',
  },
  {
    nombre: 'plato18',
    alergenos: [1, 12],
    precioMedia: 'X',
    precioEntera: '7.00',
  },
  {
    nombre: 'plato19',
    alergenos: [1, 3],
    precioMedia: 'X',
    precioEntera: '6.00',
  },
  {
    nombre: 'plato21',
    alergenos: [1, 12, 4],
    precioMedia: 'X',
    precioEntera: '5.00',
  },
  {
    nombre: 'plato22',
    alergenos: [3],
    precioMedia: 'X',
    precioEntera: '15.50',
  },
  {
    nombre: 'plato23',
    alergenos: [3, 12],
    precioMedia: 'X',
    precioEntera: '15.50',
  },
  { nombre: 'plato24', alergenos: [3], precioMedia: 'X', precioEntera: '9.00' },
  { nombre: 'plato26', alergenos: [0], precioMedia: 'X', precioEntera: '3.00' },
  { nombre: 'plato28', alergenos: [0], precioMedia: 'X', precioEntera: '3.00' },
  { nombre: 'plato30', alergenos: [0], precioMedia: 'X', precioEntera: '1.11' },
];
