import Plato from '../interfaces/plato.interface';

export const Desayunos: Plato[] = [
  { nombre: 'plato1', alergenos: [0], precioMedia: '1/2R', precioEntera: '1R' },
  { nombre: 'plato2', alergenos: [0], precioMedia: 'X', precioEntera: '1.50' },
  { nombre: 'plato3', alergenos: [0], precioMedia: 'X', precioEntera: '1.50' },
  { nombre: 'plato4', alergenos: [0], precioMedia: 'X', precioEntera: '2.50' },
  { nombre: 'plato5', alergenos: [0], precioMedia: 'X', precioEntera: '2.50' },
  { nombre: 'plato6', alergenos: [0], precioMedia: 'X', precioEntera: '1.50' },
  { nombre: 'plato7', alergenos: [0], precioMedia: 'X', precioEntera: '1.50' },
  { nombre: 'plato8', alergenos: [0], precioMedia: 'X', precioEntera: '2.50' },
  { nombre: 'plato9', alergenos: [0], precioMedia: 'X', precioEntera: '2.50' },
  { nombre: 'plato10', alergenos: [0], precioMedia: 'X', precioEntera: '2.00' },
  { nombre: 'plato11', alergenos: [1], precioMedia: 'X', precioEntera: '2.00' },
  { nombre: 'plato12', alergenos: [1], precioMedia: 'X', precioEntera: '2.00' },
  { nombre: 'plato13', alergenos: [1], precioMedia: 'X', precioEntera: '8.00' },
  { nombre: 'plato14', alergenos: [1], precioMedia: 'X', precioEntera: '5.50' },
  { nombre: 'plato15', alergenos: [1, 7, 12], precioMedia: 'X', precioEntera: '4.00' },
  { nombre: 'plato16', alergenos: [1, 12], precioMedia: 'X', precioEntera: '3.50' },
  { nombre: 'plato17', alergenos: [1, 7, 12], precioMedia: 'X', precioEntera: '5.00' },
  { nombre: 'plato18', alergenos: [1, 12], precioMedia: 'X', precioEntera: '4.50' },
  { nombre: 'plato19', alergenos: [1, 3], precioMedia: 'X', precioEntera: '3.50' },
  { nombre: 'plato20', alergenos: [0], precioMedia: 'X', precioEntera: '+1.00' },
  { nombre: 'plato21', alergenos: [1, 12, 4], precioMedia: 'X', precioEntera: '4.00' },
  { nombre: 'plato22', alergenos: [3], precioMedia: 'X', precioEntera: '12.00' },
  { nombre: 'plato23', alergenos: [3, 12], precioMedia: 'X', precioEntera: '10.00' },
  { nombre: 'plato24', alergenos: [3], precioMedia: 'X', precioEntera: '5.00' },
  { nombre: 'plato25', alergenos: [0], precioMedia: 'X', precioEntera: '1.50' },
  { nombre: 'plato26', alergenos: [0], precioMedia: 'X', precioEntera: '2.00' },
  { nombre: 'plato27', alergenos: [0], precioMedia: 'X', precioEntera: '1.50' },
  { nombre: 'plato28', alergenos: [0], precioMedia: 'X', precioEntera: '2.00' },
  { nombre: 'plato29', alergenos: [0], precioMedia: 'X', precioEntera: '0.25' },
  { nombre: 'plato30', alergenos: [0], precioMedia: 'X', precioEntera: '0.50' },
]
